// THE one place financial terms are defined in plain English (UI §3.3). Screens attach <InfoDot term=…/>
// next to a term and it shows the matching definition — so "nest egg" / "RMD" / "surplus" mean the same
// thing everywhere and are never left bare on one screen and explained on another. Seeded from the
// captions in docs/finwise-taxonomy-spec.md. Keep definitions short, jargon-free, and consistent with
// the canonical selectors (take-home = after tax + 401k; surplus = after debt; etc.).
export type GlossaryTerm =
  | 'rmd' | 'surplus' | 'nestEgg' | 'unclassified' | 'earmarked'
  | 'takeHome' | 'investable' | 'emergencyFund' | 'savingsRate' | 'netWorth' | 'nwChange'
  // asset classes (what your money is invested in) + income — added so the same plain-English meaning
  // shows wherever these appear (Net Worth classes, holdings, Income).
  | 'cash' | 'stocks' | 'bonds' | 'alternatives' | 'realEstate' | 'personalProperty'
  | 'grossIncome' | 'contributionRoom' | 'capitalGains'
  | 'safeDraw' | 'guaranteedIncome' | 'rateSensitivity' | 'provenance' | 'estimate' | 'moneyWeighted' | 'benchmark'
  | 'investments' | 'yourReturn' | 'nestEggMath' | 'priceReturn' | 'howReturnsWork';

export const GLOSSARY: Record<GlossaryTerm, { title: string; body: string }> = {
  takeHome:     { title: 'Take-home', body: 'What actually lands in your account each month — after income tax and your 401(k) contribution.' },
  surplus:      { title: 'Surplus', body: 'Your take-home minus spending minus debt payments — the money left to save or invest each month.' },
  nwChange:     { title: 'How your change and return are calculated', body: 'THE DOLLAR CHANGE — today\u2019s net worth minus your net worth on the date shown, from our own saved daily records (never a guess). It counts everything: market moves, dividends and interest, money you added or took out, property values you update, and debt principal you paid.\n\nTHE PERCENT — measured on your cash + investments only: their value today versus the start date, divided by the start value. Your home and property are left out of the percent because they only move when you retype them.\n\nTap the change line to see the full story \u2014 dividends, interest, change in investment value, and debt you paid, always summing exactly.\n\nRETURN on the Performance tab is a different number by design: it measures invested money only, counts when you added or took out money (so deposits never count as return), and a window under a year is never shown as a yearly rate.' },
  netWorth:     { title: 'Net worth', body: 'Everything you own minus everything you owe. Assets − debts.' },
  // Build-43 feedback #2: "$0 investments vs $1,500 net worth" needs the difference said in place.
  // c1 in the approved detailed design (Home tab) + the build-43 clarification ask.
  investments:  { title: 'Investments', body: 'Stocks & funds, bonds and alternatives — cash is counted separately. Your net worth is the bigger picture: everything you own (including cash, your home, and property) minus everything you owe. So you can have $0 in investments and still have a net worth.' },
  // invest-v3 FINAL (2026-07-19): returns are capped at the purchase date — say why in place.
  yourReturn:   { title: 'Your return', body: 'Each holding counts from the later of the period start or the day you bought it — so this is what happened to YOUR money, not the security\'s whole-period story. Rows counted since purchase are marked, and the market comparison uses the same dates.' },
  // Invest review 2026-07-19 (approved "all three"): say the dividends truth plainly.
  priceReturn:  { title: 'Price returns', body: 'The changes shown here track prices only — dividends and interest payments aren\'t included yet. With dividends reinvested, your actual results run a bit higher than shown (for many funds, one to two points a year). We\'d rather say that plainly than overstate precision. Full total-return tracking arrives with richer market data.' },
  // invest-v7 FINAL (2026-07-19): the ONE footnote dot — founder-approved copy, verbatim.
  howReturnsWork: { title: 'How these numbers work', body: 'Each holding is counted from the day you bought it, or the start of the selected period — whichever is later. So these are your results, not the security\'s whole-period story; rows counted from your purchase are marked.\n\nThe market comparison uses the same dates, and each holding is measured against its own yardstick — stocks against the S&P 500, bonds against the bond index — weighted the way your money actually is.\n\nOne honest note: changes track prices only. Dividends and interest aren\'t included yet, so with dividends reinvested your true results run a bit higher than shown.' },
  // lookahead-v3 FINAL + founder wording 2026-07-19 (their copy, near-verbatim).
  // Founder ask 2026-08-11: explain the whole method to someone who does not follow finance —
  // what we run, what "Monte Carlo" means, every assumption in it, and where to change them.
  nestEggMath:  { title: 'How we work out your odds', body: 'THE SHORT VERSION — nobody knows what markets will do, so we don’t pretend to. Instead we play out your whole retirement 500 times, each time with a different run of market luck, and count how often your money lasts. If it lasts in 420 of the 500, we say 84%.\n\nWHAT "MONTE CARLO" MEANS — it is named after the casino, and it means exactly what it sounds like: rolling the dice, over and over, and looking at the spread of what comes out. One tidy forecast would hide the risk; 500 rough futures show it. Each run walks year by year from today to the age you plan to, growing your savings in good years, shrinking them in bad ones, taking out what you spend, and stopping if the money hits zero.\n\nWHAT WE ASSUME\n• GROWTH — not one flat rate. We use the long-run return of what you actually hold, weighted by how much sits in each: shares grow faster than cash, so a share-heavy pot assumes more growth. Each figure comes from a named long-run yardstick (the S&P 500 for shares, a broad bond index for bonds, Treasury bills for cash).\n• THE UPS AND DOWNS — each holding also carries how much its return typically swings from year to year, from the same long-run records. That swing is what makes the 500 runs differ.\n• INFLATION — 2.5% a year, raising your spending and your Social Security as time passes.\n• WHAT YOU SPEND, WHEN YOU STOP WORKING, AND HOW LONG YOU PLAN FOR — your answers; we plan to 90 unless you say otherwise.\n• SOCIAL SECURITY AND ANY PENSION — counted from the age you claim, not before.\n• REQUIRED WITHDRAWALS — from 73 the government makes you take money out of pre-tax accounts; we take the tax on that out of your savings too.\n• BIG ONE-OFF COSTS — a roof, a wedding, a car: counted in the year you said.\n\nYOU CAN CHANGE ANY OF IT — go to the Plan tab and open Retirement. Growth rate, inflation, when you retire, what you spend, how long to plan for: change one and the odds re-run in front of you.\n\nWHAT THIS IS NOT — a promise. It is an estimate built from your numbers and the assumptions above. Two honest limits: we treat each year’s market luck as independent, though real bad years tend to arrive in clusters; and we treat your holdings as moving together, which makes the odds slightly cautious rather than flattering.' },
  benchmark:    { title: 'The market comparison', body: 'We compare each holding to a standard yardstick for its type — stocks and funds against the S&P 500 (the 500 largest US companies), bonds against a broad bond index. "Ahead by 2 points" means your money grew 2 percentage points more than that yardstick over the same period.' },
  nestEgg:      { title: 'Retirement nest egg', body: 'The invested money your retirement draws on. Excludes your home, emergency cash, and rentals — those provide income or shelter instead of being spent down.' },
  investable:   { title: 'Investable assets', body: 'Cash plus investments plus retirement accounts. Excludes your home and personal property (cars, valuables).' },
  earmarked:    { title: 'Earmarked', body: 'The share of an account you’ve set aside for retirement. Cash and property default to 0%; investment accounts to 100%.' },
  unclassified: { title: 'Unclassified', body: 'An account whose holdings we don’t know yet — counted in your total, but not shown as stocks/bonds until you set the mix.' },
  rmd:          { title: 'Required withdrawals (RMD)', body: 'Required Minimum Distribution — the amount the IRS requires you to withdraw from pre-tax retirement accounts each year starting at age 73.' },
  emergencyFund:{ title: 'Emergency fund', body: 'Cash set aside for the unexpected — a common target is 3–6 months of your essential spending.' },
  savingsRate:  { title: 'Savings rate', body: 'The share of your take-home pay you set aside each month. Around 20% is a healthy benchmark.' },
  cash:         { title: 'Cash', body: 'Money in checking, savings, or a brokerage sweep — cash only. Money-market funds and CDs pay dividends or interest, so they count under Stocks / ETFs and Bonds & CDs, where their earnings are measured.' },
  stocks:       { title: 'Stocks & ETFs', body: 'Shares of companies, or funds (ETFs) that bundle many stocks together. Higher long-term growth, with more ups and downs along the way.' },
  bonds:        { title: 'Bonds', body: 'Loans to a government or company that pay you interest (a coupon) and return the face value at maturity. Steadier than stocks; you can also sell them before maturity.' },
  alternatives: { title: 'Alternatives', body: 'Investments outside plain stocks and bonds — crypto, private equity, commodities, options. Often higher risk and harder to value.' },
  realEstate:   { title: 'Real estate', body: 'Property you own — your home, rentals, or land. Counts toward net worth; your primary home is left out of the retirement nest egg.' },
  personalProperty: { title: 'Personal property', body: 'Valuable things you own — vehicles, jewelry, collectibles. Counted in net worth, but not in investable assets.' },
  grossIncome:  { title: 'Gross income', body: 'Your total pay before any taxes or deductions. Take-home is what’s left after tax and your 401(k).' },
  contributionRoom: { title: 'Contribution room', body: 'How much more you can still add to a tax-advantaged account (401(k), IRA, HSA) this year before hitting the IRS limit.' },
  capitalGains: { title: 'Capital gains tax', body: 'Tax on profit when you sell. Held over a year: the lower long-term rate (often 15%). Held under a year: taxed like regular income. The app shows an estimate — your real rate depends on your full tax picture.' },
  safeDraw: { title: 'Safe draw', body: 'The steady monthly amount the math says your savings can support without running out before your plan-to age. Re-checked against your live balances — an estimate, not a guarantee.' },
  guaranteedIncome: { title: 'Guaranteed income', body: 'Money that arrives no matter what markets do — Social Security, a pension, an annuity. The foundation of a retirement paycheck.' },
  rateSensitivity: { title: 'Rate sensitivity', body: 'How much a bond’s market value moves if interest rates move. Rates up, existing bonds down — but held to maturity, a bond still returns its face value.' },
  provenance: { title: 'Where this number came from', body: 'Every figure shows its source — connected from your bank, imported from a file, or entered by you — and how fresh it is. You can always trace a number.' },
  moneyWeighted: { title: 'Your money-weighted return', body: 'The yearly rate your OWN dollars actually earned, counting when you put money in and took it out. Different from a fund’s posted return — timing matters. Computed from your recorded activity; an estimate.' },
  estimate: { title: 'Estimate', body: 'A figure computed from your numbers and stated assumptions — not a promise or a prediction. Change the inputs and it changes. You decide what to do with it.' },
};
